website/auth.py
import base64
import math
import re
import secrets
import sys
from dataclasses import dataclass
from datetime import UTC, datetime, timedelta
from email.headerregistry import Address as EmailAddress
from typing import Any, TypeGuard

import requests
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask.typing import ResponseReturnValue
from flask_login import AnonymousUserMixin, login_required, login_user, logout_user
from markupsafe import Markup
from MySQLdb.constants.ER import DUP_ENTRY
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from werkzeug.security import check_password_hash, generate_password_hash

from . import csp_captcha, db, production, talisman
from .mailer import send_confirmation_mail, send_password_reset_mail
from .models import EmailToken, TokenType, User
from .secrets_manager import *
from .session_utils import get_session, get_user

USERNAME_PATTERN = re.compile(r"[\w]+", flags=re.ASCII)

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login() -> ResponseReturnValue:
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password", "")

        user = db.session.scalar(select(User).where(User.email == email))
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                flash("Logged in successfully", category="success")
                return redirect(url_for("views.home"))
            else:
                flash("Incorrect password", category="error")
        else:
            flash("No user registered with this email", category="error")
    return render_template("login.html")


@auth.route("logout")
@login_required
def logout() -> ResponseReturnValue:
    logout_user()
    return redirect(url_for("auth.login"))


@auth.route("/signup", methods=["GET", "POST"])
@talisman(content_security_policy=csp_captcha)
def sign_up() -> ResponseReturnValue:
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        username = request.form.get("username")

        if check_captcha("signup"):
            user = db.session.scalar(select(User).where(User.email == email))
            if user:
                flash("This email is already registered.", category="error")
            elif username is None or len(username) < 4:
                flash("Username must be longer than 4 characters.", category="error")
            elif len(username) > 20:
                flash(
                    "Username must not be longer than 20 characters.", category="error"
                )
            elif not USERNAME_PATTERN.fullmatch(username):
                flash(
                    "Username can contain only alphanumeric characters and '-'.",
                    category="error",
                )
            elif not check_password_rules(password):
                # check_password_rules uses flash to show the errors
                pass
            elif not email:
                flash("Email is required", category="error")
            else:
                try:
                    new_user_data = User(
                        email=email,
                        username=username,
                        password=generate_password_hash(
                            password, method="scrypt:131072:8:1"
                        ),
                    )
                    db.session.add(new_user_data)
                    db.session.flush()
                    activation_token = secrets.token_bytes(32)
                    confirmation_url = url_for(
                        ".confirm_email",
                        _scheme="https",
                        _external=True,
                        token_enc=base64.urlsafe_b64encode(activation_token).decode(
                            "ascii"
                        ),
                    )
                    saved_token = EmailToken(
                        token=activation_token,
                        token_type=TokenType.mail_confirmation,
                        user_id=new_user_data.id,
                    )
                    db.session.add(saved_token)
                    send_confirmation_mail(username, email, confirmation_url)
                    db.session.commit()
                    login_user(new_user_data, remember=True)
                    flash("Account created successfully!", category="success")
                    return redirect(url_for("views.home"))
                except IntegrityError as e:
                    if e.orig and e.orig.args[0] == DUP_ENTRY:
                        flash("This username is already registered.", category="error")
                    else:
                        print(e, file=sys.stderr)
                        flash(
                            "Something went wrong. Please try again later.",
                            category="error",
                        )
                except ValueError as e:
                    # Probably invalid email
                    flash("Invalid data provided", "error")
        else:
            flash("CAPTCHA validation failed. Please try again.", category="error")
    return render_template("signup.html", recaptcha_site_key=RECAPTCHA_PUBLIC_KEY)


@auth.route("/signup/confirm/<token_enc>")
def confirm_email(token_enc: str) -> ResponseReturnValue:
    token = base64.urlsafe_b64decode(token_enc)
    valid_time = datetime.now(UTC) - timedelta(hours=48)
    matching_token = db.session.scalar(
        select(EmailToken).where(
            EmailToken.token == token,
            EmailToken.token_type == TokenType.mail_confirmation,
            EmailToken.created_on >= valid_time,
        )
    )
    if not matching_token:
        current_user = get_session()
        if isinstance(current_user, AnonymousUserMixin) or not current_user.confirmed:
            flash(
                Markup(
                    f'Invalid or expired link. You can request a new activation link on the <a href="{url_for("views.account")}">profile page</a>.'
                ),
                "error",
            )
        else:
            flash("Invalid or expired link.", "error")
        return redirect("/")

    matching_token.user.confirmed = True
    db.session.delete(matching_token)
    db.session.commit()
    flash("Email successfully confirmed. You can now upload parts.")
    return redirect("/")


@auth.route("/signup/resend-mail", methods=["POST"])
@login_required
def resend_confirmation_email() -> ResponseReturnValue:
    current_user = get_user()
    if current_user.confirmed:
        flash("Your email has already been confirmed.")
        return redirect(url_for("views.account"))

    saved_token = db.session.scalar(
        select(EmailToken).where(
            EmailToken.user_id == current_user.id,
            EmailToken.token_type == TokenType.mail_confirmation,
        )
    )
    # Allow resending email every 5 minutes
    allowed_after = (
        (saved_token.created_on + timedelta(minutes=5)) if saved_token else None
    )
    now = datetime.now(UTC)
    if allowed_after and now <= allowed_after:
        # In theory we could end up with exactly 0 s, because of <=, but the chance is very low
        wait = allowed_after - now
        wait_str = format_time_interval(wait)
        flash(
            f"Please wait {wait_str} before requesting another confirmation email.",
            "error",
        )
        return redirect(url_for("views.account"))

    activation_token = secrets.token_bytes(32)
    confirmation_url = url_for(
        ".confirm_email",
        _scheme="https",
        _external=True,
        token_enc=base64.urlsafe_b64encode(activation_token).decode("ascii"),
    )
    if saved_token:
        saved_token.token = activation_token
        saved_token.created_on = now
    else:
        saved_token = EmailToken(
            token=activation_token,
            token_type=TokenType.mail_confirmation,
            user_id=current_user.id,
        )
        db.session.add(saved_token)

    send_confirmation_mail(current_user.username, current_user.email, confirmation_url)
    db.session.commit()
    flash("An email with a confirmation link was sent.")
    return redirect(url_for("views.account"))


@auth.route("/reset-password", methods=["GET", "POST"])
@talisman(content_security_policy=csp_captcha)
def forgot_password() -> ResponseReturnValue:
    if request.method == "POST":
        email = request.form.get("email")

        if check_captcha("forgot_password"):
            user = db.session.scalar(select(User).where(User.email == email))
            if user:
                now = datetime.now(UTC)
                saved_token = db.session.scalar(
                    select(EmailToken)
                    .where(
                        EmailToken.user_id == user.id,
                        EmailToken.token_type == TokenType.password_reset,
                    )
                    .order_by(EmailToken.created_on.desc())
                )
                created_on = (
                    saved_token.created_on if saved_token else datetime.min
                ).replace(tzinfo=UTC)
                resend_if_after = created_on + timedelta(minutes=1)
                if now < resend_if_after:
                    wait = resend_if_after - now
                    wait_str = format_time_interval(wait)
                    flash(
                        f"Please wait {wait_str} before requesting another password reset email.",
                        "error",
                    )
                    return render_template(
                        "forgot-password.html",
                        recaptcha_site_key=RECAPTCHA_PUBLIC_KEY,
                    )

                else:
                    if saved_token:
                        db.session.delete(saved_token)

website/templates/account.html
{% extends "base.html" %}
{% block title %}Account{% endblock %}
{% block navbar_add_class %}masthead-no-img{% endblock %}
{% block header%}
<header class="masthead masthead-no-img">
    <div class="masthead-heading text-uppercase">Account</div>
</header>
{% endblock %}

{% block content %}
<section class="bg-secondary-subtle">
    <div class="container py-5">
      {% if not user.confirmed %}
      <div class="alert alert-warning" role="alert">
        <form method="post" action="{{ url_for('auth.resend_confirmation_email') }}">
          <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
          Your email has not been confirmed - the ability to upload parts is restricted and the account may be deleted after some time.
          If you did not receive the email with an activation link you can <button class="btn btn-link p-0 border-0 align-baseline">resend the email</button>.
        </form>
      </div>
      {% endif %}
      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">
              {% if user.image %}
                  <img src="{{ url_for('static', filename='uploads/profile_images/' + user.image) }}" alt="avatar" class="profile-img">
              {% else %}
                <picture>
                  <source srcset="{{ url_for('static', filename='assets/img/opt/default_avatar.avif') }}" type="image/avif">
                  <source srcset="{{ url_for('static', filename='assets/img/opt/default_avatar.webp') }}" type="image/webp">
                  <source srcset="{{ url_for('static', filename='assets/img/opt/default_avatar.jxl') }}" type="image/jxl">
                  <img src="{{ url_for('static', filename='assets/img/opt/default_avatar.png') }}" alt="default avatar" class="profile-img">
                </picture>
              {% endif %}
              <h5 class="my-3">{{ user.username }}</h5>
              <p class="text-body-secondary mb-1">{{ user.description if user.description else "" }}</p>
            </div>
          </div>
          <div class="card mb-4 mb-lg-0">
            <div class="card-body p-0">
              <ul class="list-group list-group-flush rounded-3">
                <!-- <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fa-solid fa-globe fa-lg text-warning"></i>
                  <p class="mb-0">https://indystry.cc</p>
                </li> -->
                {% if user.name_github %}
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fa-brands fa-github fa-lg social-gh me-2"></i>
                  <p class="mb-0 overflow-x-auto"><a href="https://github.com/{{ user.name_github }}" target="_blank">{{user.name_github}}</a></p>
                </li>
                {% endif %}
                {% if user.name_youtube %}
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fa-brands fa-youtube fa-lg social-yt me-2"></i>
                  <p class="mb-0 overflow-x-auto"><a href="https://youtube.com/@{{ user.name_youtube }}" target="_blank">{{user.name_youtube}}</a></p>
                </li>
                {% endif %}
                {% if user.name_instagram %}
                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                  <i class="fa-brands fa-instagram fa-lg social-ig me-2"></i>
                  <p class="mb-0 overflow-x-auto"><a href="https://instagram.com/{{ user.name_instagram }}" target="_blank">{{user.name_instagram}}</a></p>
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Username</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-body-secondary mb-0">{{ user.username }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-body-secondary mb-0">{{ user.email }}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Password</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-body-secondary mb-0"><a href ="">Click to change</a></p>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                  <div class="card-body">
                      <p class="mb-4">Recent parts</p>
                      {% for part in recent_parts %}
                      <p class="mb-1 fs-6"><a href ="/part:{{part.id}}">{{ part.name }}</a></p>
                      <hr>
                      {% endfor %}
                  </div>
              </div>
          </div>
            <div class="col-md-6">
              <div class="card mb-4 mb-md-0">
                <div class="card-body">
                  <p class="mb-4">Your contribution</p>
                  <p class="mb-1 text-body-secondary">Total parts: {{total_parts}}</p>
                  <hr>
                  <p class="mt-2 mb-2 text-body-secondary">Your parts: {{user_parts}}</p>
                  <hr>
                  <p class="mt-2 mb-2 text-body-secondary">Your contribution: {{user_contribution}}%</p>
                </div>
              </div>

              <div class="card-body text-center mt-4">
                <a href="/accountsettings">Edit profile</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

website/templates/addpart.html
{% extends "base.html" %}
{% block title %}Add Part{% endblock %}
{% block navbar_add_class %}masthead-no-img{% endblock %}
{% block header %}
<header class="masthead masthead-no-img">
    <div class="masthead-heading text-uppercase">Add Part</div>
</header>
{% endblock %}

{% block content %}
<section class="bg-secondary-subtle">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Upload Part</h5>
                        <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
                            <div class="mb-3">
                                <label for="image" class="form-label">Image</label>
                                <input type="file" class="form-control" id="image" name="image" accept="{{ image_types|join(', ') }}" aria-describedby="imageHelp" data-max-size="5M" data-feedback="imageFeedback" required>
                                <div id="imageHelp" class="form-text">Minimum dimensions are 548x411 px, but not more than 64 MPx or 5 MiB.</div>
                                <div class="invalid-feedback" id="imageFeedback">A thumbnail is required (max size 5 MiB).</div>
                                <div id="image-preview"></div>
                            </div>
                            <div class="mb-3">
                                <label for="filesInput" class="form-label">Files</label>
                                <input type="file" class="form-control" name="files" id="filesInput" accept="{{ part_extensions|join(', ') }}" aria-describedby="fileHelp" data-max-files="20" data-max-size="10M" data-feedback="fileFeedback" multiple required>
                                <div id="fileHelp" class="form-text">Max. file size 10 MiB, up to 20 files allowed.</div>
                                <div class="invalid-feedback" id="fileFeedback">At least one file (model or drawing) is required.</div>
                                <div id="file-preview" class="mt-2">
                                    <div>
                                        <i class="fa-solid fa-file me-2"></i>
                                        <span>No file selected</span>
                                    </div>
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="name" name="name"
                                    placeholder="Enter the part name" maxlength="200" required>
                                <div class="invalid-feedback">Enter part name (max 200 characters)</div>
                            </div>
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea class="form-control" id="description" name="description"
                                    placeholder="Enter the part description" maxlength="5000" required></textarea>
                                <div class="invalid-feedback">Enter part description (max 5000 characters)</div>
                            </div>
                            <div class="mb-3">
                                <label for="category" class="form-label">Category</label>
                                <select class="form-select" id="category" name="category" required>
                                    {% for category in categories %}
                                        <optgroup label="{{category.name}}">
                                            {% for subcategory in category.subcategories %}
                                            <option value="{{subcategory.id}}">{{subcategory.name}}</option>
                                            {% endfor %}
                                        </optgroup>
                                    {% endfor %}
                                </select>
                                <div class="invalid-feedback">Select an appropriate category</div>
                            </div>
                            <div class="mb-3">
                                <label for="tags" class="form-label">Tags</label>
                                <input type="text" class="form-control" id="tags" name="tags"
                                    placeholder="Enter tags separated by commas" autocomplete="off" maxlength="200">
                                <div class="invalid-feedback">Maximum length is 200 characters</div>
                            </div>
                            <button type="submit" class="btn btn-primary">Upload</button>
                            <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                        </form>
                        <div class="mt-4 small">
                            <p class="small">By uploading your parts to OpenRoboticPlatform, you are joining a community dedicated to open collaboration in robotics. To foster seamless collaboration and knowledge sharing, all parts uploaded to OpenRoboticPlatform are released under the MIT license.</p>
                            <p class="small">With the MIT license, you retain ownership of your parts while allowing others to build upon your work, whether for personal, educational, or commercial purposes.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<script src="{{ url_for('static', filename='js/parent-in-select.js') }}" type="module" nonce="{{ csp_nonce() }}"></script>
<script src="{{ url_for('static', filename='js/image-preview.js') }}" type="module" nonce="{{ csp_nonce() }}"></script>
<script src="{{ url_for('static', filename='js/file-preview.js') }}" type="module" nonce="{{ csp_nonce() }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap-form-validation.js') }}" type="module" nonce="{{ csp_nonce() }}"></script>
{% endblock %}

website/templates/admin-categories.html
{% extends "base.html" %}
{% block title %}Admin categories{% endblock %}
{% block navbar_add_class %}masthead-no-img{% endblock %}
{% block header %}
<header class="masthead masthead-no-img">
    <div class="masthead-heading text-uppercase">Admin categories</div>
</header>
{% endblock %}

{% block content %}
<section class="bg-secondary-subtle">
    <div class="container py-5 d-flex justify-content-center">
        <div class="col-12 col-sm-10 col-lg-8">
            <div class="accordion" id="accordionCategories">
            {% for category in categories %}
                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button type="button" class="accordion-button collapsed" data-bs-toggle="collapse" data-bs-target="#collapse{{ category.id }}" aria-expanded="false" aria-controls="collapse{{ category.id }}">{{ category.name }}</button>
                    </h2>
                    <div id="collapse{{ category.id }}" class="accordion-collapse collapse" data-bs-parent="#accordionCategories">
                        <div class="accordion-body">
                            <div class="mb-2">
                                <button class="btn btn-link p-0 border-0" data-bs-toggle="modal" data-bs-target="#categoryEditModal" data-category-id="{{ category.id }}" data-category-name="{{ category.name }}">Edit category <i class="fa-solid fa-pen-to-square"></i></button><br>
                                Subcategories:
                            </div>
                            <ul class="list-group list-group-flush">
                            {% for subcategory in category.subcategories %}
                                <ul class="list-group-item d-flex justify-content-between align-items-center">
                                    {{ subcategory.name }}
                                    <button class="btn btn-link p-0 border-0"  data-bs-toggle="modal" data-bs-target="#categoryEditModal" data-category-id="{{ subcategory.id }}" data-category-name="{{ subcategory.name }}" data-parent-id="{{ category.id }}">Edit <i class="fa-solid fa-pen-to-square"></i></button>
                                </ul>
                            {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
            </div>
            <button class="btn btn-primary mt-3" data-bs-toggle="modal" data-bs-target="#categoryEditModal" data-category-id="-1"><i class="fa-solid fa-circle-plus"></i> New category</button>
        </div>
    </div>
</section>
<div class="modal fade" id="categoryEditModal" tabindex="-1" aria-labelledby="categoryEditLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="categoryEditLabel">New category</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="categoryModalForm" method="post">
                    <div class="mb-3">
                        <label for="categoryName" class="col-form-label">Category name:</label>
                        <input type="text" class="form-control" id="categoryName" name="categoryName" minlength="1" maxlength="50">
                    </div>
                    <div class="mb-3">
                        <label for="parentCategory" class="col-form-label">Parent category:</label>
                        <select class="form-select" id="parentCategory" name="parentCategory">
                            <option value="-1">None (main category)</option>
                            {% for category in categories %}
                            <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <input type="text" class="d-none" id="categoryId" name="categoryId">
                    <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="submit" form="categoryModalForm" class="btn btn-primary">Create category</button>
            </div>
        </div>
    </div>
</div>
<script type="module" src="{{ url_for('static', filename='js/admin-categories.js') }}" nonce="{{ csp_nonce() }}"></script>
{% endblock %}

website/templates/adminpanel.html
{% extends "base.html" %}
{% block title %}Admin Panel{% endblock %}
{% block navbar_add_class %}masthead-no-img{% endblock %}
{% block header%}
<header class="masthead masthead-no-img">
    <div class="masthead-heading text-uppercase">Admin Panel</div>
</header>
{% endblock %}
{% block content %}
<div class="container container-all">
  <h2 class="mt-4">Manage Parts</h2>
  <table class="table">
    <thead>
        <tr>
            <th>Image</th>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Author</th>
            <th>Views</th>
            <th>Verified</th>
            <th>Featured</th>
            <th>Public</th>
            <th>Rejected</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for part in parts %}
        <tr>
            <td name="image">
              <div class="card-img-container">
                <img src="{{ url_for('static', filename='uploads/images/' + part.image) }}" alt="Part Image" class="card-img-top" />
             </div>
            </td>
            <td name="id">{{ part.id }}</td>
            <td name="name"><a href="{{ url_for('views.part', part_number=part.id) }}">{{ part.name }}</a></td>
            <td>{% if part.cat.parent_cat %}{{ part.cat.parent_cat.name }} - {% endif %}{{ part.cat.name }}</td>
            <td>{{ part.author.username }}</td>
            <td>{{ part.views }}</td>
            <td>
              <input class="form-check-input" type="radio" {% if part.verified %}checked{% endif %} disabled>
            </td>
            <td>
              <input class="form-check-input" type="radio" {% if part.featured %}checked{% endif %} disabled>
            </td>
            <td>
              <input class="form-check-input" type="radio" {% if part.public %}checked{% endif %} disabled>
            </td>
            <td>
              <input class="form-check-input" type="radio" {% if part.rejected %}checked{% endif %} disabled>
            </td>
            <td>
              <a href="{{ url_for('views_admin.editPart', part_number=part.id) }}"><button class="btn btn-primary btn-sm edit-button">Edit</button></a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>


  <nav aria-label="Pagination">
    <ul class="pagination">
      {% if parts.has_prev %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('views_admin.panel', page=parts.prev_num) }}">Previous</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Previous</span>
      </li>
      {% endif %}

      {% for num in parts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if num %}
          {% if parts.page == num %}
            <li class="page-item active">
              <span class="page-link">{{ num }}</span>
            </li>
          {% else %}
            <li class="page-item">
              <a class="page-link" href="{{ url_for('views_admin.panel', page=num) }}">{{ num }}</a>
            </li>
          {% endif %}
        {% else %}
          <li class="page-item disabled">
            <span class="page-link">...</span>
          </li>
        {% endif %}
      {% endfor %}

      {% if parts.has_next %}
      <li class="page-item">
        <a class="page-link" href="{{ url_for('views_admin.panel', page=parts.next_num) }}">Next</a>
      </li>
      {% else %}
      <li class="page-item disabled">
        <span class="page-link">Next</span>
      </li>
      {% endif %}
    </ul>
  </nav>
</div>
{% endblock %}